# Generated by Django 4.2.6 on 2023-11-20 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
